# Generated by Django 2.2.5 on 2019-11-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardquestion',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
