# Generated by Django 2.2.5 on 2019-11-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easyquestion',
            name='is_pass',
        ),
        migrations.RemoveField(
            model_name='hardquestion',
            name='is_pass',
        ),
        migrations.RemoveField(
            model_name='mediumquestion',
            name='is_pass',
        ),
    ]
