# Generated by Django 2.2.5 on 2019-11-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191122_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easyquestion',
            name='is_passed',
        ),
        migrations.RemoveField(
            model_name='hardquestion',
            name='is_passed',
        ),
        migrations.RemoveField(
            model_name='mediumquestion',
            name='is_passed',
        ),
        migrations.AddField(
            model_name='easyquestion',
            name='score',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='hardquestion',
            name='score',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='mediumquestion',
            name='score',
            field=models.IntegerField(default=3),
        ),
    ]
