# Generated by Django 2.2.5 on 2019-11-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20191123_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyquestion',
            name='hint',
            field=models.IntegerField(default=-2),
        ),
        migrations.AddField(
            model_name='hardquestion',
            name='hint',
            field=models.IntegerField(default=-2),
        ),
        migrations.AddField(
            model_name='mediumquestion',
            name='hint',
            field=models.IntegerField(default=-2),
        ),
    ]
