# Generated by Django 2.2.5 on 2019-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20191123_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyquestion',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hardquestion',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediumquestion',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
    ]
