# Generated by Django 2.2.5 on 2019-11-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20191124_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easyquestion',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='hardquestion',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='mediumquestion',
            name='hint',
        ),
    ]
