# Generated by Django 2.1.2 on 2019-11-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_score',
            field=models.IntegerField(default=0),
        ),
    ]
