# Generated by Django 2.2.5 on 2019-11-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='all_score',
            field=models.IntegerField(default=4),
        ),
    ]
