# Generated by Django 2.2.5 on 2019-11-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_score',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
